### ISSUE TITLE
Dependência não encontrada

### ISSUE THREAD

**Issue by cleitonsb** [brunodsazevedo/react-native-pagseguro-plugpag#4]
Prezados, bom dia. Logo na configuração inicial estou recebendo um erro por falta de uma dependencia da lib do pagseguro:

> Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find br.com.uol.pagseguro.plugpagservice.wrapper:wrapper:1.7.6.
     Required by:
         project :app

Poderiam me esclarecer o que pode estar faltando?

**Comment by brunodsazevedo** [comment]
@cleitonsb A ultima versão está com bug mesmo e está sendo corrigida.

**Comment by cleitonsb** [comment]
> @cleitonsb A ultima versão está com bug mesmo e está sendo corrigida.

Qual é a versão recomendada para uso? 0.1.0?

**Comment by brunodsazevedo** [comment]
> > @cleitonsb A ultima versão está com bug mesmo e está sendo corrigida.
> 
> Qual é a versão recomendada para uso? 0.1.0?

Sim... ela está com a build normal... está apenas com problema no método de impressão.
