### ISSUE TITLE
Utilizando Minizinha

### ISSUE THREAD

**Issue by theogmn** [brunodsazevedo/react-native-pagseguro-plugpag#6]
Essa lib tem suporte para conexão com a Minizinha NFC? Caso não tenha, alguém tem uma solução? 
Preciso conectar um terminal à um totem android com uma aplicação React Native.
Desde já agradecido.

**Comment by brunodsazevedo** [comment]
@theogmn infelizmente não tive a oportunidade de integrar a lib para leitura de NFC. E acredito que no teu caso, essa lib não teria suporte ao terminal da Minizinha, apenas para terminais do tipo Smart, como Moderniha Smart, Moderniha Smart 2, entre outros terminais do tipo Smart.
